// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: peer/filepb/file.proto

package filepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServeFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkData []byte `protobuf:"bytes,1,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
}

func (x *ServeFileResponse) Reset() {
	*x = ServeFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peer_filepb_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServeFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeFileResponse) ProtoMessage() {}

func (x *ServeFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peer_filepb_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeFileResponse.ProtoReflect.Descriptor instead.
func (*ServeFileResponse) Descriptor() ([]byte, []int) {
	return file_peer_filepb_file_proto_rawDescGZIP(), []int{0}
}

func (x *ServeFileResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

type ServeFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *ServeFileRequest) Reset() {
	*x = ServeFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peer_filepb_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServeFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeFileRequest) ProtoMessage() {}

func (x *ServeFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peer_filepb_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeFileRequest.ProtoReflect.Descriptor instead.
func (*ServeFileRequest) Descriptor() ([]byte, []int) {
	return file_peer_filepb_file_proto_rawDescGZIP(), []int{1}
}

func (x *ServeFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

var File_peer_filepb_file_proto protoreflect.FileDescriptor

var file_peer_filepb_file_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x65, 0x65, 0x72, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x62, 0x2f, 0x66, 0x69,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x65, 0x65, 0x72, 0x22, 0x32,
	0x0a, 0x11, 0x53, 0x65, 0x72, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x2f, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x32, 0x52, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x43, 0x0a, 0x0c, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x65, 0x65,
	0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x65, 0x65,
	0x72, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_peer_filepb_file_proto_rawDescOnce sync.Once
	file_peer_filepb_file_proto_rawDescData = file_peer_filepb_file_proto_rawDesc
)

func file_peer_filepb_file_proto_rawDescGZIP() []byte {
	file_peer_filepb_file_proto_rawDescOnce.Do(func() {
		file_peer_filepb_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_peer_filepb_file_proto_rawDescData)
	})
	return file_peer_filepb_file_proto_rawDescData
}

var file_peer_filepb_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_peer_filepb_file_proto_goTypes = []interface{}{
	(*ServeFileResponse)(nil), // 0: peer.ServeFileResponse
	(*ServeFileRequest)(nil),  // 1: peer.ServeFileRequest
}
var file_peer_filepb_file_proto_depIdxs = []int32{
	1, // 0: peer.FileService.DownloadFile:input_type -> peer.ServeFileRequest
	0, // 1: peer.FileService.DownloadFile:output_type -> peer.ServeFileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_peer_filepb_file_proto_init() }
func file_peer_filepb_file_proto_init() {
	if File_peer_filepb_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_peer_filepb_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServeFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peer_filepb_file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServeFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_peer_filepb_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_peer_filepb_file_proto_goTypes,
		DependencyIndexes: file_peer_filepb_file_proto_depIdxs,
		MessageInfos:      file_peer_filepb_file_proto_msgTypes,
	}.Build()
	File_peer_filepb_file_proto = out.File
	file_peer_filepb_file_proto_rawDesc = nil
	file_peer_filepb_file_proto_goTypes = nil
	file_peer_filepb_file_proto_depIdxs = nil
}
